### ISSUE TITLE
Renaming Genus2Signature? 

### ISSUE THREAD

**Issue by eamonnaobrien** [algeboy/Auto-Sandbox#15]
Josh wrote:
The intrinsic `Genus2Signature` changed to `TGSignature` and acceptable input broadened. 

I believe the following crash is a consequence.

> Q:= PCGroup(\[ 10, -5, 5, 5, 5, 5, -5, 5, 5, 5, 5, 7875101, 52032002, 656266\
2,
> 236005003, 26013, 25223, 441437504, 787514, 782524, 781534 ]);
> A := AutomorphismGroupByInvariants (Q);
process i =  3
process i =  4

AutomorphismGroupByInvariants(
    G: GrpPC
)
[/home/eobr007/Stabiliser/Auto-Sandbox/src/isom-test.m:1](
)
In file "/home/eobr007/Stabiliser/Auto-Sandbox/src/bimap_labels.m", line 57, 
column 8:
>> return Genus2Signature (s);
          ^
Runtime error: Undefined reference 'Genus2Signature' in package 
"/home/eobr007/Stabiliser/Auto-Sandbox/src/bimap_labels.m"

Best wishes.
Eamonn

**Comment by joshmaglione** [comment]
Thanks, fixed this issue.
